---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates a lambda function for the SupportChatBot workshop

Resources:
  SupportChatBot:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "supportchatbot-east-1"
        S3Key: "lambda/support-chatbot-function.zip"
      Description: "Lambda code for the Support Chatbot"
      FunctionName: "support-chatbot-function"
      Handler: "index.handler"
      Role: !GetAtt ChatbotExecutionRole.Arn
      Runtime: "python2.7"
      Timeout: 25

  ChatbotExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /supportchatbot/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: CognitoChatbotLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Sid: AllowLogging
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              -
                Sid: CognitoManageUser
                Effect: Allow
                Action:
                  - "cognito-idp:AdminDisableUser"
                  - "cognito-idp:AdminResetUserPassword"
                Resource:
                  - !Sub "arn:aws:cognito-idp:*:*:userpool/*"
                  - !Sub "arn:aws:cognito-idp:*:*:userpool/*"
